import Footer from './components/footer'
import React from 'react'
import Header from './components/header'
import './globals.css'
import {aboutMeData,pages,contactMeLinks} from './data/data'



export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body >
        <Header name={aboutMeData.name} pages={pages} />
        <main className='sm:mb-32 mb-16'>

        {children}
        </main>
        <Footer contactMeLinks={contactMeLinks}/>
      </body>
    </html>
  )
}
